darts.py
FireLemons/Probability-Programs pull request #17
Opened 2020-10-12 15:10 UTC by tincher

2020-10-14 00:18 UTC, FireLemons commented
I'm a bit busy irl so give me a little while to review. I'll be done wither tomorrow or the next day

2020-10-14 14:02 UTC, FireLemons requested changes

2020-10-14 14:02 UTC, FireLemons commented on book_programs/chapter_2/darts.py
> +#import matplotlib.pyplot as pyplot for graphing
delete this comment
`#import matplotlib.pyplot as pyplot for graphing`

2020-10-14 14:02 UTC, FireLemons commented on book_programs/chapter_2/darts.py
> +        print(current_distance)
~~delete these lines because the distances of the darts is always displayed~~
Actually this looks a lot neater than the `print("Distances of the darts: ", dart_distances)` at the bottom of the script.  
Could you truncate the distances to 3 decimal points and also print `"Distances of the darts: "` before the loop?

2020-10-14 14:02 UTC, FireLemons commented on book_programs/chapter_2/darts.py
> +print("Distances of the darts: ", dart_distances)
~~the output of this is quite rough to look at. Maybe truncate the distances to 3 decimal points.~~
delete and use the distance print in the loop above instead

2020-10-14 14:02 UTC, FireLemons commented on book_programs/chapter_2/darts.py
> +print("Distances of the darts: ", dart_distances)
in the mathematica script, the list of distances is hidden for mute_output instead of the area bar graph. Could you please edit the script so it matches? Especially because the textbook recommends calling darts for n=1000

2020-10-14 14:18 UTC, tincher commented
I implemented all your requests.
I hope everything is okay now.

2020-10-15 13:14 UTC, merged

2020-10-15 13:14 UTC, FireLemons commented
great work